"""
Signal and information environment.

Signals are the mechanism by which ground truth reaches agents — imperfectly.
Each signal has:
  - precision: how informative (0 = noise, 1 = perfect)
  - cost: how expensive to produce (costly signals are more credible)
  - lag: turns of delay before delivery
  - bias: systematic distortion (disinformation)
  - reach: which agents receive it

Costly signaling theory: actions update beliefs more than words,
weighted by cost. A missile launch (expensive, irreversible) is a
high-precision signal. A tweet is cheap talk.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from .beliefs import BeliefVar


# ---------------------------------------------------------------------------
# Signal taxonomy
# ---------------------------------------------------------------------------

class SignalType(Enum):
    """Categories of signals with different credibility profiles."""

    # Costly signals — high precision, expensive to fake
    MILITARY_ACTION = "military_action"        # strikes, launches, movements
    TERRITORIAL_CHANGE = "territorial_change"  # ground gained/lost
    CASUALTY_REPORT = "casualty_report"        # own-side (costly to admit)
    ECONOMIC_DATA = "economic_data"            # market prices, trade flows

    # Medium-cost signals
    SATELLITE_IMAGERY = "satellite_imagery"    # high precision but lagged
    SIGINT = "sigint"                          # intercepted communications
    DIPLOMATIC_ACTION = "diplomatic_action"    # formal diplomatic moves
    FORCE_DEPLOYMENT = "force_deployment"      # troop/ship movements

    # Cheap talk — low precision, easy to fake
    PUBLIC_STATEMENT = "public_statement"      # leader statements, tweets
    MEDIA_REPORT = "media_report"              # news coverage
    SOCIAL_MEDIA = "social_media"              # twitter/telegram
    PROXY_CLAIM = "proxy_claim"               # proxy group claims

    # Deliberately noisy
    DISINFORMATION = "disinformation"          # planted false signals
    AMBIGUOUS_ACTION = "ambiguous_action"      # actions designed to be unclear


# Default signal properties by type
SIGNAL_PROFILES: dict[SignalType, dict] = {
    SignalType.MILITARY_ACTION: {
        "base_precision": 0.8,
        "cost": 0.9,
        "credibility_weight": 1.0,
    },
    SignalType.TERRITORIAL_CHANGE: {
        "base_precision": 0.9,
        "cost": 1.0,
        "credibility_weight": 1.0,
    },
    SignalType.CASUALTY_REPORT: {
        "base_precision": 0.5,   # often inflated/deflated
        "cost": 0.6,
        "credibility_weight": 0.7,
    },
    SignalType.ECONOMIC_DATA: {
        "base_precision": 0.85,
        "cost": 0.3,
        "credibility_weight": 0.9,
    },
    SignalType.SATELLITE_IMAGERY: {
        "base_precision": 0.9,
        "cost": 0.2,
        "credibility_weight": 0.95,
        "default_lag": 3,        # 3-day delay per scenario
    },
    SignalType.SIGINT: {
        "base_precision": 0.7,
        "cost": 0.1,
        "credibility_weight": 0.8,
    },
    SignalType.DIPLOMATIC_ACTION: {
        "base_precision": 0.6,
        "cost": 0.5,
        "credibility_weight": 0.7,
    },
    SignalType.FORCE_DEPLOYMENT: {
        "base_precision": 0.75,
        "cost": 0.7,
        "credibility_weight": 0.85,
    },
    SignalType.PUBLIC_STATEMENT: {
        "base_precision": 0.2,
        "cost": 0.05,
        "credibility_weight": 0.3,
    },
    SignalType.MEDIA_REPORT: {
        "base_precision": 0.3,
        "cost": 0.05,
        "credibility_weight": 0.35,
    },
    SignalType.SOCIAL_MEDIA: {
        "base_precision": 0.15,
        "cost": 0.01,
        "credibility_weight": 0.2,
    },
    SignalType.PROXY_CLAIM: {
        "base_precision": 0.25,
        "cost": 0.1,
        "credibility_weight": 0.3,
    },
    SignalType.DISINFORMATION: {
        "base_precision": 0.0,   # no real information content
        "cost": 0.1,
        "credibility_weight": 0.0,
    },
    SignalType.AMBIGUOUS_ACTION: {
        "base_precision": 0.3,
        "cost": 0.4,
        "credibility_weight": 0.4,
    },
}


# ---------------------------------------------------------------------------
# Signal
# ---------------------------------------------------------------------------

@dataclass
class Signal:
    """
    A single piece of information entering the system.

    Signals are generated by agent actions, world events, or the
    information environment. They propagate to receiving agents
    with noise, lag, and potential bias.
    """

    # What variable this signal is about
    variable: BeliefVar

    # The ground-truth-adjacent value (what actually happened)
    true_value: float

    # Signal properties
    signal_type: SignalType
    precision: float = 0.5       # override base precision if needed
    bias: float = 0.0            # systematic distortion
    lag: int = 0                 # turns before delivery

    # Who generated it
    source_agent: Optional[str] = None

    # Who receives it — None means broadcast to all
    recipients: Optional[list[str]] = None

    # Turn it was generated
    generated_turn: int = 0

    # Metadata for logging
    description: str = ""

    def __post_init__(self):
        profile = SIGNAL_PROFILES.get(self.signal_type, {})
        if self.precision == 0.5 and "base_precision" in profile:
            self.precision = profile["base_precision"]
        if self.lag == 0 and "default_lag" in profile:
            self.lag = profile["default_lag"]

    def noisy_value(self) -> float:
        """
        The value an agent actually perceives — true value + noise + bias.

        Noise is inversely proportional to precision.
        """
        if self.precision >= 1.0:
            return max(0.0, min(1.0, self.true_value + self.bias))

        # Noise standard deviation: high precision = low noise
        noise_std = (1.0 - self.precision) * 0.3
        noise = random.gauss(0, noise_std)

        observed = self.true_value + self.bias + noise
        return max(0.0, min(1.0, observed))

    def effective_precision(self, receiver_trust: float = 1.0) -> float:
        """
        Effective precision for a specific receiver.

        Accounts for:
        - Base signal precision
        - Costly signaling weight (expensive signals are more credible)
        - Receiver's trust in the source
        """
        profile = SIGNAL_PROFILES.get(self.signal_type, {})
        credibility = profile.get("credibility_weight", 0.5)

        return self.precision * credibility * receiver_trust


# ---------------------------------------------------------------------------
# Agent signal access — who sees what, and how
# ---------------------------------------------------------------------------

@dataclass
class SignalAccess:
    """
    Defines an agent's access to information channels.

    Different agents have radically different information environments.
    The IRGC sees SIGINT but not US internal deliberations.
    Trump sees media coverage but not IRGC missile counts.
    China sees trade data clearly but military actions through fog.
    """

    # Trust level per source agent (0-1). Affects how much weight
    # is given to signals from that source.
    source_trust: dict[str, float] = field(default_factory=dict)

    # Signal types this agent has access to, with quality modifiers
    # e.g., IRGC has degraded SIGINT access: {"sigint": 0.5}
    channel_quality: dict[SignalType, float] = field(default_factory=dict)

    # Interpretation bias per variable — how the agent systematically
    # misreads certain types of information.
    # e.g., IRGC reads US_POLITICAL_WILL with bias -0.1 (they assume
    # US is less committed than it really is)
    interpretation_bias: dict[BeliefVar, float] = field(default_factory=dict)

    # Default trust for unknown sources
    default_trust: float = 0.5

    def get_trust(self, source: Optional[str]) -> float:
        if source is None:
            return 1.0  # world events have no source bias
        return self.source_trust.get(source, self.default_trust)

    def get_channel_quality(self, signal_type: SignalType) -> float:
        return self.channel_quality.get(signal_type, 1.0)

    def get_interpretation_bias(self, var: BeliefVar) -> float:
        return self.interpretation_bias.get(var, 0.0)

    def process_signal(self, signal: Signal) -> tuple[float, float, float]:
        """
        Process a signal through this agent's information filters.

        Returns: (observed_value, effective_precision, total_bias)
        """
        trust = self.get_trust(signal.source_agent)
        channel_q = self.get_channel_quality(signal.signal_type)
        interp_bias = self.get_interpretation_bias(signal.variable)

        # Effective precision degraded by channel quality and trust
        eff_precision = signal.effective_precision(trust) * channel_q

        # Total bias = signal's inherent bias + agent's interpretation bias
        total_bias = signal.bias + interp_bias

        # Observed value includes noise
        observed = signal.noisy_value()

        return observed, eff_precision, total_bias


# ---------------------------------------------------------------------------
# Information environment — manages signal flow each turn
# ---------------------------------------------------------------------------

@dataclass
class InfoEnvironment:
    """
    The global information environment.

    Manages signal generation, propagation, lag queues, and delivery.
    Also tracks information degradation (news volume drops, internet
    shutdowns, satellite delays).
    """

    # Signals waiting to be delivered (lagged)
    pending_signals: list[tuple[int, Signal]] = field(default_factory=list)
    # (delivery_turn, signal)

    # Global information quality modifier (0-1)
    # Drops with internet shutdowns, news fatigue, etc.
    global_info_quality: float = 1.0

    # Per-region information quality
    region_info_quality: dict[str, float] = field(default_factory=lambda: {
        "iran_domestic": 0.6,    # internet degraded
        "gulf": 0.8,             # some disruption
        "global": 0.9,           # news fatigue (-54%)
    })

    # Signal log for analysis
    signal_history: list[Signal] = field(default_factory=list)

    def emit_signal(self, signal: Signal, current_turn: int) -> None:
        """Emit a signal into the environment."""
        signal.generated_turn = current_turn
        delivery_turn = current_turn + signal.lag

        if signal.lag == 0:
            # Immediate delivery — still goes through pending for
            # uniform processing
            self.pending_signals.append((current_turn, signal))
        else:
            self.pending_signals.append((delivery_turn, signal))

        self.signal_history.append(signal)

    def get_signals_for_turn(self, turn: int) -> list[Signal]:
        """Get all signals ready for delivery on this turn."""
        ready = []
        remaining = []
        for delivery_turn, signal in self.pending_signals:
            if delivery_turn <= turn:
                ready.append(signal)
            else:
                remaining.append((delivery_turn, signal))
        self.pending_signals = remaining
        return ready

    def deliver_signals(
        self,
        turn: int,
        agents: dict[str, tuple[object, SignalAccess]],
    ) -> dict[str, list[tuple[Signal, float, float, float]]]:
        """
        Deliver all ready signals to their recipients.

        Returns dict of agent_id -> [(signal, observed_val, precision, bias)]
        for logging/analysis.
        """
        signals = self.get_signals_for_turn(turn)
        deliveries: dict[str, list] = {aid: [] for aid in agents}

        for signal in signals:
            # Determine recipients
            if signal.recipients is not None:
                targets = signal.recipients
            else:
                targets = list(agents.keys())

            for agent_id in targets:
                if agent_id not in agents:
                    continue

                agent, access = agents[agent_id]
                observed, precision, bias = access.process_signal(signal)

                # Apply global info quality degradation
                precision *= self.global_info_quality

                deliveries[agent_id].append(
                    (signal, observed, precision, bias)
                )

        return deliveries

    def degrade_info(self, region: str, amount: float) -> None:
        """Degrade information quality in a region (e.g., internet shutdown)."""
        if region in self.region_info_quality:
            self.region_info_quality[region] = max(
                0.1, self.region_info_quality[region] - amount
            )

    def restore_info(self, region: str, amount: float) -> None:
        """Restore information quality."""
        if region in self.region_info_quality:
            self.region_info_quality[region] = min(
                1.0, self.region_info_quality[region] + amount
            )
